### ISSUE TITLE
FIDO2: Number of credentials

### ISSUE THREAD

**Issue by fminoridev** [fido-alliance/conformance-tools-issues#532]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authenticator

## What is the version of the tool are you using?

1.3.0

## What is the OS and the version are you running?

Windows10 v19.03 (18362.418)

## Issue description

The test named "options" fails for my authenticator since the authenticator doesn't return the numberOfCredentials.
The tool shows the following message: 

```
Resident-Key Test Resident-Key support

...
 
P-3 FOR AUTHENTICATORS WITHOUT A DISPLAY AND EITHER UV IS TRUE OR CLIENTPIN IS USED If UV option is supported, set UV to true. Else set new pin, and run registrations with pin. Else skip this test. Send two valid CTAP2 authenticatorMakeCredential(0x01) message, "options" containg an "rk" option set to true, and if authenticator supports UV option set "uv" to false, wait for the responses, and check that Authenticator returns CTAP1_ERR_SUCCESS(0x00) error code. Send a valid CTAP2 authenticatorGetAssertion(0x02) message, with no allowList presented, wait for the response and check that Authenticator returns CTAP1_ERR_SUCCESS(0x00) error code. Check that response contains "numberOfCredentials" field that is of type Number and is set to 2. Send authenticatorGetNextAssertion(0x08), until numberOfCredentials is 1, retrieve responses and check that Authenticator returns CTAP1_ERR_SUCCESS(0x00) error code for each of the requests. Check that response.user contains all of the registered userInfo‣

AssertionError: 2 credentials been registered! Expected 3, got undefined: expected undefined to equal 2

    at setUpPinIfAvailable.then.then.then.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2790:24)

    at <anonymous>
```
Since the authenticator has a display, it doesn't return the numberOfCredentials in the reply according to the CTAP specification which states [CTAP - 5.2. authenticatorGetAssertion (0x02)]:

*"Total number of account credentials for the RP. This member is required when more than one account for the RP and **the authenticator does not have a display**. Omitted when returned for the authenticatorGetNextAssertion method."*  

So the tool should not check the numberOfCredentials when the authenticator haven't a display.

**Comment by herrjemand** [comment]
> This member is required when more than one account for the RP and the authenticator does not have a display.

This means that this thing is for the authenticators that do not have a display and have more than one credential for specified RP

**Comment by fminoridev** [comment]
Yes, correct. But the tool right now checks numberOfCredentials even when I select ok when the tool says: "Does your authenticator support display", so my authenticator can't never pass the test.
Please fix it.

**Comment by FabianHenneke** [comment]
This seems to be caused by #526, the test should simply not run for authenticators with displays.
